"""Generation-path tests for #120 after the ownership switch to Beacon.

The graph side is a fake in-memory reader; Beacon owns projection and
serialization through the real ``beacon build`` CLI in a separate
interpreter, and Menhir keeps only the evidence dump and guarded
publication. These tests require MENHIR_TEST_BEACON_PYTHON to point at an
absolute path to a Python interpreter whose Beacon CLI supports the
build+validate contract; there is no stub or skip fallback.
"""

from __future__ import annotations

import hashlib
import os
import subprocess
import sys
from pathlib import Path
from types import SimpleNamespace

import pytest
import yaml

from menhir.infrastructure.project_scanner import ProjectScanner
from menhir.services import beacon_generation as generation_module
from menhir.services.beacon_compat import BeaconCompatError, beacon_python_is_usable
from menhir.services.beacon_generation import BeaconGenerationError, generate_beacon
from tests.test_beacon_evidence import _reader


def _fixture_repo(tmp_path: Path) -> Path:
    """A fixture repository whose cited canonical docs exist on disk."""
    (tmp_path / "docs").mkdir(parents=True, exist_ok=True)
    (tmp_path / "README.md").write_text(
        "# Fixture project for the evidence dump.\n", encoding="utf-8"
    )
    (tmp_path / "docs" / "architecture.md").write_text(
        "# Architecture\nLayered design.\n", encoding="utf-8"
    )
    return tmp_path


@pytest.fixture
def beacon_python() -> str:
    """Absolute path to a Python interpreter with the Beacon build contract.

    Required via MENHIR_TEST_BEACON_PYTHON; generation runs the real Beacon
    CLI in an isolated subprocess, so there is no stub or skip fallback.
    """
    raw = os.environ.get("MENHIR_TEST_BEACON_PYTHON", "").strip()
    if not raw:
        pytest.fail(
            "MENHIR_TEST_BEACON_PYTHON is not set: these tests run the real Beacon "
            "CLI in a subprocess. Set it to the absolute path of a Python "
            "interpreter whose Beacon supports build+validate, e.g. "
            "MENHIR_TEST_BEACON_PYTHON=/opt/beacon-venv/bin/python"
        )
    interpreter = Path(raw)
    if not interpreter.is_absolute():
        pytest.fail(f"MENHIR_TEST_BEACON_PYTHON must be an absolute path, got {raw!r}")
    if not interpreter.is_file():
        pytest.fail(
            f"MENHIR_TEST_BEACON_PYTHON does not point at an existing interpreter file: {raw!r}"
        )
    return str(interpreter)


def test_contract_gate_rejects_interpreter_without_beacon() -> None:
    """Menhir's own interpreter has no Beacon: the contract probe must refuse it."""
    with pytest.raises(BeaconCompatError):
        beacon_python_is_usable(sys.executable)


def test_generate_creates_valid_artifact(beacon_python: str, tmp_path: Path) -> None:
    repo = _fixture_repo(tmp_path)
    reader = _reader(root=str(repo))
    expected_fingerprint = ProjectScanner().scan(repo).scan_fingerprint
    outcome = generate_beacon(reader, "fixture", repo, beacon_python=beacon_python)
    assert outcome.created is True
    assert outcome.output_path == repo / "beacon.generated.yaml"
    payload = outcome.output_path.read_bytes()
    assert outcome.sha256 == hashlib.sha256(payload).hexdigest()
    assert payload.startswith(b"# Generated by Menhir beacon v1\n")
    # Beacon owns the content: the manifest schema marker and the
    # evidence-backed description must both be present, mapped by Beacon.
    assert b"beacon_version: '0.1'" in payload or b'beacon_version: "0.1"' in payload
    assert b"Fixture project for the evidence dump." in payload
    assert b"status: experimental" in payload
    # The scan fingerprint is persisted as a citation in the artifact.
    assert expected_fingerprint.encode() in payload
    # A generated manifest always ends with exactly one trailing newline.
    assert payload.endswith(b"\n") and not payload.endswith(b"\n\n")


def test_scanner_indexed_documents_never_publish_role_none(
    beacon_python: str, tmp_path: Path
) -> None:
    """PR #125 F1, end to end through the real reader and the real Beacon.

    Scanner-written document nodes have no ``document_type`` property; the graph returns it as
    None. The reader used to hand over the string ``"None"`` and Beacon published ``role: None``.
    """
    from unittest.mock import MagicMock

    from menhir.infrastructure.structure_queries import StructureGraphWriter

    repo = _fixture_repo(tmp_path)
    neo4j = MagicMock()
    neo4j.execute.return_value = [
        {"name": "README.md", "path": "README.md", "description": None,
         "root_path": None, "doc_type": None},
        {"name": "architecture.md", "path": "docs/architecture.md", "description": None,
         "root_path": None, "doc_type": None},
    ]
    reader = _reader(root=str(repo))
    reader.query_documents = StructureGraphWriter(neo4j=neo4j).query_documents

    outcome = generate_beacon(reader, "fixture", repo, beacon_python=beacon_python)

    manifest = yaml.safe_load(outcome.output_path.read_text(encoding="utf-8"))
    docs = manifest["canonical_docs"]
    assert {d["path"] for d in docs} == {"README.md", "docs/architecture.md"}
    assert [d["role"] for d in docs] == ["generic", "generic"]
    assert b"role: None" not in outcome.output_path.read_bytes()


def test_generate_refuses_existing_output(beacon_python: str, tmp_path: Path) -> None:
    repo = _fixture_repo(tmp_path)
    (repo / "beacon.generated.yaml").write_bytes(b"# existing\n")
    with pytest.raises(BeaconGenerationError, match="refusing to overwrite"):
        generate_beacon(
            _reader(root=str(repo)), "fixture", repo, beacon_python=beacon_python
        )


def test_refresh_is_cas_guarded(beacon_python: str, tmp_path: Path) -> None:
    repo = _fixture_repo(tmp_path)
    reader = _reader(root=str(repo))
    first = generate_beacon(reader, "fixture", repo, beacon_python=beacon_python)
    target = repo / "beacon.generated.yaml"
    original = target.read_bytes()

    wrong = "0" * 64
    with pytest.raises(BeaconGenerationError, match="does not match existing"):
        generate_beacon(
            reader,
            "fixture",
            repo,
            beacon_python=beacon_python,
            refresh=True,
            expected_sha256=wrong,
        )

    refreshed = generate_beacon(
        reader,
        "fixture",
        repo,
        beacon_python=beacon_python,
        refresh=True,
        expected_sha256=first.sha256,
    )
    assert refreshed.created is False
    assert refreshed.sha256 == first.sha256
    assert target.read_bytes() == original  # unchanged rebuild: byte-identical


def test_refresh_requires_expected_sha256(beacon_python: str, tmp_path: Path) -> None:
    repo = _fixture_repo(tmp_path)
    with pytest.raises(BeaconGenerationError, match="expected-sha256"):
        generate_beacon(
            _reader(root=str(repo)),
            "fixture",
            repo,
            beacon_python=beacon_python,
            refresh=True,
        )


def test_source_edit_during_beacon_build_refuses_publication(
    beacon_python: str, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    repo = _fixture_repo(tmp_path)
    reader = _reader(root=str(repo))
    first = generate_beacon(reader, "fixture", repo, beacon_python=beacon_python)
    target = repo / "beacon.generated.yaml"
    original = target.read_bytes()
    real_build = generation_module.build_manifest_via_beacon

    def build_then_edit(*args, **kwargs):
        payload = real_build(*args, **kwargs)
        (repo / "README.md").write_text("# Edited during Beacon build\n", encoding="utf-8")
        return payload

    monkeypatch.setattr(generation_module, "build_manifest_via_beacon", build_then_edit)
    with pytest.raises(BeaconGenerationError, match="stale"):
        generate_beacon(
            reader,
            "fixture",
            repo,
            beacon_python=beacon_python,
            refresh=True,
            expected_sha256=first.sha256,
        )
    assert target.read_bytes() == original


def test_reingest_during_beacon_build_refuses_publication(
    beacon_python: str, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    repo = _fixture_repo(tmp_path)
    reader = _reader(root=str(repo))
    first = generate_beacon(reader, "fixture", repo, beacon_python=beacon_python)
    target = repo / "beacon.generated.yaml"
    original = target.read_bytes()
    real_build = generation_module.build_manifest_via_beacon

    def build_then_reingest(*args, **kwargs):
        payload = real_build(*args, **kwargs)
        reader._guard_state["writer_revision"] = "writer-2"
        return payload

    monkeypatch.setattr(
        generation_module, "build_manifest_via_beacon", build_then_reingest
    )
    with pytest.raises(BeaconGenerationError, match="structure changed"):
        generate_beacon(
            reader,
            "fixture",
            repo,
            beacon_python=beacon_python,
            refresh=True,
            expected_sha256=first.sha256,
        )
    assert target.read_bytes() == original


def test_changed_source_fact_changes_only_its_claim(
    beacon_python: str, tmp_path: Path
) -> None:
    repo = _fixture_repo(tmp_path)
    reader = _reader(root=str(repo))
    generate_beacon(reader, "fixture", repo, beacon_python=beacon_python)
    before = (repo / "beacon.generated.yaml").read_text(encoding="utf-8")

    changed = _reader(
        root=str(repo),
        overview={
            "description": "A changed evidence dump description.",
            "stack": "python",
            "entities": {"file": 3},
            "edges": {"IMPORTS": 2},
            "coverage": {"known": True},
            "contains_repos": [],
        },
    )
    generate_beacon(
        changed,
        "fixture",
        repo,
        beacon_python=beacon_python,
        refresh=True,
        expected_sha256=hashlib.sha256(before.encode("utf-8")).hexdigest(),
    )
    after = (repo / "beacon.generated.yaml").read_text(encoding="utf-8")

    before_lines = before.splitlines()
    after_lines = after.splitlines()
    assert len(before_lines) == len(after_lines)
    changed_indexes = [
        index for index, (a, b) in enumerate(zip(before_lines, after_lines)) if a != b
    ]
    assert changed_indexes, "the changed fact must be reflected"
    for index in changed_indexes:
        assert "Fixture project for the evidence dump." in before_lines[index]
        assert "A changed evidence dump description." in after_lines[index]


def test_artifact_serves_without_menhir(beacon_python: str, tmp_path: Path) -> None:
    """Validate and export the artifact with Menhir completely out of the loop."""
    repo = _fixture_repo(tmp_path)
    generate_beacon(
        _reader(root=str(repo)), "fixture", repo, beacon_python=beacon_python
    )
    manifest = repo / "beacon.generated.yaml"

    probe = subprocess.run(  # nosec B603 - fixed argv, local fixture only
        [beacon_python, "-m", "beacon", "validate", str(manifest)],
        capture_output=True,
        check=False,
        cwd=str(repo),
    )
    assert probe.returncode == 0, probe.stderr.decode("utf-8", errors="replace")
    assert b"0 errors" in probe.stdout

    # Export is publication-strict: the two known-absent intent warnings must
    # be acknowledged (with the same fixed reasons the build used).
    ack_guardrails = "--acknowledge=guardrails_missing=generated from source evidence"
    ack_test = "--acknowledge=test_command_missing=generated from source evidence"
    exported = subprocess.run(  # nosec B603 - fixed argv, local fixture only
        [
            beacon_python,
            "-m",
            "beacon",
            "export",
            str(manifest),
            "--output",
            "-",
            ack_guardrails,
            ack_test,
        ],
        capture_output=True,
        check=False,
        cwd=str(repo),
    )
    assert exported.returncode == 0, exported.stderr.decode("utf-8", errors="replace")
    assert b'"beacon_snapshot_version":"1.0"' in exported.stdout


def test_cli_reader_uses_canonical_structure_adapter(monkeypatch: pytest.MonkeyPatch) -> None:
    """Exercise the real lazy adapter import without opening a database connection."""
    from menhir.cli.beacon import _reader as cli_reader
    from menhir.config.settings_model import MemorySettings
    from menhir.infrastructure.structure_queries import StructureGraphWriter

    settings = SimpleNamespace(
        neo4j_uri="bolt://127.0.0.1:7689",
        neo4j_user="neo4j",
        neo4j_password="fixture-only",
        neo4j_database="neo4j",
    )
    monkeypatch.setattr("menhir.env_file.load_menhir_env", lambda: None)
    monkeypatch.setattr(MemorySettings, "from_env", staticmethod(lambda: settings))
    reader, repository = cli_reader()
    try:
        assert isinstance(reader, StructureGraphWriter)
        assert reader.neo4j is repository
        assert repository.uri == settings.neo4j_uri
        for method in (
            "get_project_root_path", "get_project_coverage", "get_scan_fingerprint",
            "query_overview", "query_files", "query_documents", "get_beacon_evidence_guard",
        ):
            assert callable(getattr(reader, method))
    finally:
        repository.close()
