"""Publication safety tests for #120; no Beacon or graph dependency."""

from __future__ import annotations

import hashlib
from pathlib import Path

import pytest

from menhir.services.beacon_publication import PublicationError, publish_manifest


PAYLOAD = b'# Generated by Menhir beacon v1\n{"beacon_version":"0.1"}\n'


def accept(path: Path) -> None:
    assert path.read_bytes() == PAYLOAD


def test_failed_validation_preserves_existing_manifest(tmp_path: Path) -> None:
    target = tmp_path / "beacon.generated.yaml"
    target.write_bytes(PAYLOAD)

    def reject(path: Path) -> None:
        raise ValueError("invalid evidence")

    with pytest.raises(ValueError, match="invalid evidence"):
        publish_manifest(tmp_path, PAYLOAD, validate=reject,
                         expected_sha256=hashlib.sha256(PAYLOAD).hexdigest())
    assert target.read_bytes() == PAYLOAD
    assert sorted(p.name for p in tmp_path.iterdir()) == [target.name]


def test_create_and_explicit_refresh(tmp_path: Path) -> None:
    digest = publish_manifest(tmp_path, PAYLOAD, validate=accept)
    assert digest == hashlib.sha256(PAYLOAD).hexdigest()
    target = tmp_path / "beacon.generated.yaml"
    before = target.stat().st_mtime_ns
    assert publish_manifest(tmp_path, PAYLOAD, validate=accept, expected_sha256=digest) == digest
    assert target.stat().st_mtime_ns == before


def test_creation_never_overwrites_and_wrong_digest_refused(tmp_path: Path) -> None:
    publish_manifest(tmp_path, PAYLOAD, validate=accept)
    for expected in (None, "0" * 64):
        with pytest.raises(PublicationError):
            publish_manifest(tmp_path, PAYLOAD, validate=accept, expected_sha256=expected)
    assert (tmp_path / "beacon.generated.yaml").read_bytes() == PAYLOAD


def test_hand_authored_sidecar_refused_even_with_matching_digest(tmp_path: Path) -> None:
    original = b"project: hand-authored\n"
    (tmp_path / "beacon.generated.yaml").write_bytes(original)
    with pytest.raises(PublicationError):
        publish_manifest(tmp_path, PAYLOAD, validate=accept,
                         expected_sha256=hashlib.sha256(original).hexdigest())
    assert (tmp_path / "beacon.generated.yaml").read_bytes() == original


def test_validation_time_edit_preserved(tmp_path: Path) -> None:
    target = tmp_path / "beacon.generated.yaml"
    target.write_bytes(PAYLOAD)

    def intervening_edit(path: Path) -> None:
        target.write_bytes(b"user edited during validation")

    with pytest.raises(PublicationError):
        publish_manifest(tmp_path, PAYLOAD, validate=intervening_edit,
                         expected_sha256=hashlib.sha256(PAYLOAD).hexdigest())
    assert target.read_bytes() == b"user edited during validation"


def test_before_publish_refusal_preserves_existing_manifest(tmp_path: Path) -> None:
    target = tmp_path / "beacon.generated.yaml"
    target.write_bytes(PAYLOAD)
    calls: list[str] = []

    def refuse() -> None:
        calls.append("guard")
        raise ValueError("source changed")

    with pytest.raises(ValueError, match="source changed"):
        publish_manifest(
            tmp_path,
            PAYLOAD,
            validate=accept,
            before_publish=refuse,
            expected_sha256=hashlib.sha256(PAYLOAD).hexdigest(),
        )
    assert calls == ["guard"]
    assert target.read_bytes() == PAYLOAD


def test_existing_lock_and_invalid_payload_refused(tmp_path: Path) -> None:
    lock = tmp_path / ".beacon.generated.lock"
    lock.write_text("another operation", encoding="utf-8")
    with pytest.raises(PublicationError):
        publish_manifest(tmp_path, PAYLOAD, validate=accept)
    assert lock.read_text() == "another operation"
    lock.unlink()
    with pytest.raises(PublicationError):
        publish_manifest(tmp_path, b"not a generated artifact", validate=accept)
    assert not list(tmp_path.iterdir())


def test_canonical_manifest_untouched(tmp_path: Path) -> None:
    canonical = tmp_path / "beacon.yaml"
    canonical.write_text("hand-authored", encoding="utf-8")
    publish_manifest(tmp_path, PAYLOAD, validate=accept)
    assert canonical.read_text() == "hand-authored"
