"""Configuration-file writes for ``menhir setup``: .env upserts, provider blocks, and secret ACLs.

Split out of :mod:`menhir.cli.setup`, which re-exports the public names so existing import
sites keep working unchanged.
"""

from __future__ import annotations

import os
import subprocess
import sys
from pathlib import Path

#: Providers `menhir setup --provider` can make fully consistent: the two that back
#: chat, Graphiti extraction, and embeddings end to end.
SETUP_PROVIDERS = ("local", "openai")

#: Keys written for each provider. A value of ``None`` means "ensure the key exists,
#: never overwrite a non-empty value" -- used for secrets the operator fills in.
_PROVIDER_KEYS: dict[str, dict[str, str | None]] = {
    "local": {
        "LLM_CHAT_PROVIDER": "local",
        "GRAPHITI_LLM_PROVIDER": "local",
        "GRAPHITI_EMBED_PROVIDER": "local",
        "LOCAL_LLM_BASE_URL": None,
        "LOCAL_LLM_CHAT_MODEL": None,
        "LOCAL_LLM_EMBED_MODEL": None,
    },
    "openai": {
        "LLM_CHAT_PROVIDER": "openai",
        "GRAPHITI_LLM_PROVIDER": "openai",
        "GRAPHITI_EMBED_PROVIDER": "openai",
        "OPENAI_API_KEY": None,
        "OPENAI_CHAT_MODEL": None,
        "OPENAI_EMBED_MODEL": None,
    },
}

#: Credentials matching the root docker-compose.yml Neo4j service.
COMPOSE_NEO4J_KEYS: dict[str, str | None] = {
    "NEO4J_URI": "bolt://localhost:7687",
    "NEO4J_USER": "neo4j",
    "NEO4J_PASSWORD": "password",
    "NEO4J_DATABASE": "neo4j",
}


def _split_env_line(line: str) -> tuple[str, str, str] | None:
    """Return (prefix, key, value) for ``KEY=value`` or ``# KEY=value`` lines, else None."""

    stripped = line.lstrip()
    prefix = ""
    if stripped.startswith("#"):
        prefix = "#"
        stripped = stripped[1:].lstrip()
    if "=" not in stripped:
        return None
    key, _, value = stripped.partition("=")
    key = key.strip()
    if not key or not all(ch.isalnum() or ch == "_" for ch in key):
        return None
    return prefix, key, value


def upsert_env_keys(env_path: Path, updates: dict[str, str | None]) -> list[str]:
    """Set keys in a dotenv file, preserving every other line. Returns the changes made.

    - An active ``KEY=`` line is rewritten in place (only when the value differs).
    - A commented ``# KEY=`` line is uncommented in place.
    - A missing key is appended.
    - ``None`` values mean *ensure present*: an existing active line with a non-empty
      value is left untouched, otherwise ``KEY=`` is written so the operator sees what
      to fill in. Secrets therefore never get overwritten by re-running setup.
    """

    lines = env_path.read_text(encoding="utf-8").split("\n") if env_path.exists() else [""]
    changes: list[str] = []
    active_idx: dict[str, int] = {}
    commented_idx: dict[str, int] = {}
    for i, line in enumerate(lines):
        parsed = _split_env_line(line)
        if parsed is None:
            continue
        prefix, key, _ = parsed
        if prefix == "" and key not in active_idx:
            active_idx[key] = i
        elif prefix == "#" and key not in commented_idx:
            commented_idx[key] = i

    for key, desired in updates.items():
        if key in active_idx:
            i = active_idx[key]
            _, _, current = _split_env_line(lines[i])  # type: ignore[misc]
            current = current.strip()
            if desired is None:
                continue  # ensure-present only; an active line already satisfies it
            if current != desired:
                lines[i] = f"{key}={desired}"
                changes.append(f"set {key}")
            continue
        value = "" if desired is None else desired
        if key in commented_idx:
            lines[commented_idx[key]] = f"{key}={value}"
            changes.append(f"enabled {key}")
            continue
        if lines and lines[-1] == "":
            lines.insert(len(lines) - 1, f"{key}={value}")
        else:
            lines.append(f"{key}={value}")
        changes.append(f"added {key}")

    if changes:
        env_path.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    return changes


#: Written into a generated `.env` when there is no checkout to copy `.env.example` from.
#: Deliberately short: the annotated template lives in the repository, and `menhir check`
#: names any key that is actually missing, so duplicating 380 lines of commentary into the
#: wheel would only create a second copy to drift.
_GENERATED_ENV_HEADER = """# Menhir configuration, generated by `menhir setup` outside a source checkout.
# Full annotated template: https://github.com/Archolith/menhir/blob/main/.env.example
# `menhir check` names every key still needed.
"""

#: The bundled Neo4j `--compose-neo4j` starts when there is no repository compose file. Kept
#: byte-identical to the repository's docker-compose.yml; the credentials match
#: COMPOSE_NEO4J_KEYS, which setup writes into .env at the same time.
_GENERATED_COMPOSE = """services:
  neo4j:
    image: neo4j:5-community
    container_name: menhir-neo4j
    environment:
      NEO4J_AUTH: neo4j/password
      NEO4J_PLUGINS: '["apoc"]'
    ports:
      - "7474:7474"   # Browser UI
      - "7687:7687"   # Bolt protocol
    volumes:
      - neo4j_data:/data

volumes:
  neo4j_data:
"""


def _restrict_secret_file(path: Path) -> list[str]:
    """Tighten a secret-bearing file's ACL on Windows, where ``chmod`` cannot (CF-43).

    ``os.chmod`` on win32 toggles ONE bit -- the read-only attribute -- and does nothing to the
    ACL. So ``env_path.chmod(0o600)`` above is correct and sufficient on POSIX and inert on the
    platform this project is primarily developed on: the file stays readable by every account on
    the machine. The finding was closed on the POSIX half alone.

    `icacls` is the supported way to do this without a pywin32 dependency: strip inheritance and
    grant only the current user. Best-effort by design -- a setup command must not fail because
    an ACL could not be tightened, and the caller is told either way rather than being left to
    assume it worked.
    """
    if sys.platform != "win32":
        return []

    user = os.environ.get("USERNAME") or ""
    if not user:
        return [f"WARNING: could not restrict {path}: USERNAME is unset"]
    domain = os.environ.get("USERDOMAIN") or ""
    # Joined rather than interpolated: a literal backslash inside an f-string is an escape
    # sequence waiting to be mangled, and DOMAIN\user is exactly the shape icacls expects.
    principal = "\\".join([domain, user]) if domain else user

    try:
        completed = subprocess.run(
            ["icacls", str(path), "/inheritance:r", "/grant:r", f"{principal}:F"],
            capture_output=True,
            text=True,
            timeout=20,
            check=False,
        )
    except (OSError, subprocess.SubprocessError) as exc:
        return [f"WARNING: could not restrict {path} to {principal}: {exc}"]

    if completed.returncode != 0:
        detail = (completed.stderr or completed.stdout or "").strip().splitlines()
        return [
            f"WARNING: could not restrict {path} to {principal}: "
            f"icacls exited {completed.returncode}: {detail[0] if detail else 'no output'}"
        ]
    return [f"restricted {path} to {principal} (ACL)"]
