"""Publication of generated beacon manifests (issue #120).

A beacon manifest is published to a single fixed path
(``root/beacon.generated.yaml``) while a cooperating, single-operator advisory
lock is held. This module coordinates *cooperating* writers on a trusted
filesystem only; it deliberately makes no claim of atomic compare-and-swap
safety against a hostile filesystem or non-cooperating concurrent writers.
"""

from __future__ import annotations

import hashlib
import os
import tempfile
from collections.abc import Callable
from pathlib import Path

__all__ = ["PublicationError", "publish_manifest"]

_PREFIX = b"# Generated by Menhir beacon v1\n"
_MAX_PAYLOAD_BYTES = 1024 * 1024
_OUTPUT_NAME = "beacon.generated.yaml"
_LOCK_NAME = ".beacon.generated.lock"
_STAGE_PREFIX = ".beacon.generated."
_STAGE_SUFFIX = ".tmp"
_HEX_DIGITS = frozenset("0123456789abcdef")


class PublicationError(ValueError):
    """Raised when a beacon manifest cannot be published safely."""


def _sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def _check_payload(payload: bytes) -> None:
    if not isinstance(payload, bytes):
        raise PublicationError("payload must be bytes")
    if not payload.startswith(_PREFIX):
        raise PublicationError("payload is missing the generated-by beacon prefix")
    if len(payload) > _MAX_PAYLOAD_BYTES:
        raise PublicationError("payload exceeds the 1 MiB limit")


def _check_root(root: Path) -> None:
    if root.is_symlink():
        raise PublicationError(f"root must not be a symlink: {root}")
    if not root.exists():
        raise PublicationError(f"root does not exist: {root}")
    if not root.is_dir():
        raise PublicationError(f"root is not a directory: {root}")


def _check_expected(expected: str) -> str:
    if not isinstance(expected, str) or len(expected) != 64:
        raise PublicationError("expected_sha256 must be 64 lowercase hex characters")
    if any(char not in _HEX_DIGITS for char in expected):
        raise PublicationError("expected_sha256 must be 64 lowercase hex characters")
    return expected


def _inspect_target(target: Path) -> bytes | None:
    """Return current target bytes, or None when it does not yet exist."""

    if target.is_symlink():
        raise PublicationError(f"target must not be a symlink: {target}")
    if not target.exists():
        return None
    if not target.is_file():
        raise PublicationError(f"target is not a regular file: {target}")
    return target.read_bytes()


def _acquire_lock(lock_path: Path) -> int:
    try:
        return os.open(lock_path, os.O_CREAT | os.O_EXCL | os.O_WRONLY, 0o600)
    except FileExistsError as exc:
        raise PublicationError(f"lock already held: {lock_path}") from exc


def _stage_candidate(root: Path, payload: bytes) -> str:
    fd, stage_path = tempfile.mkstemp(
        dir=root, prefix=_STAGE_PREFIX, suffix=_STAGE_SUFFIX
    )
    with os.fdopen(fd, "wb") as handle:
        handle.write(payload)
        handle.flush()
        os.fsync(handle.fileno())
    return stage_path


def _cleanup(stage_path: str | None, lock_fd: int | None, owned_lock: Path | None) -> None:
    """Remove only the temp file and lock this call created."""

    if stage_path is not None:
        try:
            os.unlink(stage_path)
        except FileNotFoundError:
            pass
    if lock_fd is not None:
        os.close(lock_fd)
    if owned_lock is not None:
        try:
            os.unlink(owned_lock)
        except FileNotFoundError:
            pass


def publish_manifest(
    root: Path,
    payload: bytes,
    *,
    validate: Callable[[Path], None],
    expected_sha256: str | None = None,
) -> str:
    """Publish ``payload`` as ``root/beacon.generated.yaml``; return its sha256."""

    _check_payload(payload)
    _check_root(root)

    target = root / _OUTPUT_NAME
    existing = _inspect_target(target)

    expected: str | None = None
    if expected_sha256 is None:
        if existing is not None:
            raise PublicationError(f"refusing to overwrite existing output: {target}")
    else:
        expected = _check_expected(expected_sha256)
        if existing is None:
            raise PublicationError("expected_sha256 given but no existing output")
        if not existing.startswith(_PREFIX):
            raise PublicationError("existing output is missing the beacon prefix")
        if _sha256(existing) != expected:
            raise PublicationError("expected_sha256 does not match existing output")

    digest = _sha256(payload)
    lock_path = root / _LOCK_NAME
    lock_fd: int | None = None
    owned_lock: Path | None = None
    stage_path: str | None = None
    try:
        lock_fd = _acquire_lock(lock_path)
        owned_lock = lock_path

        stage_path = _stage_candidate(root, payload)
        validate(Path(stage_path))

        if Path(stage_path).read_bytes() != payload:
            raise PublicationError("staged candidate changed after validation")

        # Validation may have been slow: re-inspect the target before mutating it.
        current = _inspect_target(target)
        if expected is None:
            if current is not None:
                raise PublicationError(f"output appeared during publication: {target}")
            try:
                os.link(stage_path, target)
            except FileExistsError as exc:
                raise PublicationError(
                    f"output appeared during publication: {target}"
                ) from exc
        else:
            if current is None:
                raise PublicationError("target disappeared during validation")
            if _sha256(current) != expected:
                raise PublicationError("target changed during validation")
            if current == payload:
                return digest  # identical bytes: preserve mtime, skip replacement
            os.replace(stage_path, target)
        return digest
    finally:
        _cleanup(stage_path, lock_fd, owned_lock)
