"""Beacon-owned generation from Menhir-held project knowledge (issue #120).

Ownership switched 2026-09-18: Menhir no longer maps Beacon manifest fields.
The bespoke raw-manifest construction that lived here (identity block,
structure concept, canonical-doc selection, guidance block) was a second
manifest-mapping implementation maintained against Beacon's schema; it is
gone. Menhir now dumps a versioned evidence document
(:mod:`menhir.services.beacon_evidence`) and Beacon's own pipeline —
``beacon build`` with its ``MenhirSourceAdapter``, authority policy, and
deterministic projection — produces the manifest. Menhir keeps only what it
must own:

* the evidence dump (its indexed facts, fail-closed); and
* publication safety (:mod:`menhir.services.beacon_publication`: prefix
  check, advisory lock, atomic replace, compare-and-swap refresh), fed the
  exact bytes Beacon streamed to stdout.

Every emitted claim is produced and cited by Beacon; ``beacon validate``
(through the compat boundary) gates publication. Nothing here invents facts,
and refreshes are CAS-guarded by the caller-supplied expected digest.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from menhir.services.beacon_compat import (
    beacon_python_is_usable,
    build_manifest_via_beacon,
    validate_manifest_file,
)
from menhir.services.beacon_evidence import (
    BeaconEvidenceError,
    BeaconEvidenceProjectReader,
    capture_evidence,
    require_evidence_guard,
    write_evidence_document,
)
from menhir.services.beacon_publication import (
    PublicationError,
    publish_manifest,
)

__all__ = ["BeaconGenerationError", "generate_beacon"]

#: Fixed provenance comment Beacon prepends to the generated manifest. The
#: value is also Beacon-independent publication's prefix contract, so it is
#: defined once here and passed through.
GENERATED_NOTE = "Generated by Menhir beacon v1"


class BeaconGenerationError(ValueError):
    """Raised when generation cannot proceed (evidence, contract, or publication)."""


@dataclass(frozen=True)
class GenerationOutcome:
    output_path: Path
    sha256: str
    created: bool
    scan_fingerprint: str


def generate_beacon(
    reader: BeaconEvidenceProjectReader,
    project: str,
    repo_root: Path,
    *,
    beacon_python: str,
    refresh: bool = False,
    expected_sha256: str | None = None,
) -> GenerationOutcome:
    """Generate or refresh the Beacon manifest for an indexed local project.

    Flow: dump the evidence document (fail-closed index checks) -> run
    ``beacon build`` in the caller-supplied Beacon interpreter (Beacon owns
    projection and serialization) -> publish through the guarded publication
    path (create refuses overwrites; refresh is a compare-and-swap on
    ``expected_sha256``) -> validate the staged file with Beacon's validator
    before it lands.
    """
    if bool(expected_sha256) != refresh:
        raise BeaconGenerationError(
            "refresh requires --expected-sha256; initial generation must not pass one"
        )
    beacon_python_is_usable(beacon_python)
    try:
        evidence, evidence_guard = capture_evidence(reader, project, repo_root)
    except BeaconEvidenceError as exc:
        raise BeaconGenerationError(str(exc)) from exc

    evidence_path = write_evidence_document(evidence, repo_root)
    try:
        payload = build_manifest_via_beacon(
            beacon_python,
            repo_root=repo_root,
            evidence_path=evidence_path,
            note=GENERATED_NOTE,
        )
    finally:
        try:
            evidence_path.unlink()
        except OSError:
            pass

    def validate(staged: Path) -> None:
        validate_manifest_file(beacon_python, staged)

    try:
        digest = publish_manifest(
            repo_root,
            payload,
            validate=validate,
            before_publish=lambda: require_evidence_guard(
                reader, project, repo_root, evidence_guard
            ),
            expected_sha256=expected_sha256,
        )
    except (BeaconEvidenceError, PublicationError) as exc:
        raise BeaconGenerationError(str(exc)) from exc
    target = repo_root / "beacon.generated.yaml"
    created = expected_sha256 is None
    return GenerationOutcome(
        output_path=target,
        sha256=digest,
        created=created,
        scan_fingerprint=str(evidence["project"]["scan_fingerprint"]),
    )
