"""Source-grounded Beacon manifest generation from Menhir-held project knowledge.

Conservative v1 mapping (issue #120): only indexed structural identity and
indexed documents are published. Purpose, commands, guardrails, and semantic
memories are NOT synthesized to fill schema fields; every emitted claim cites
its indexed source. Generation fails closed when required evidence is missing
or when the graph's record of the project does not match the requested root.
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Protocol

from menhir.services.beacon_compat import (
    BeaconCompatError,
    beacon_python_is_usable,
    build_manifest_via_beacon,
    validate_manifest_file,
)
from menhir.services.beacon_publication import (
    PublicationError,
    publish_manifest,
)

__all__ = ["BeaconGenerationError", "BeaconProjectReader", "generate_beacon"]

GENERATED_PREFIX = "# Generated by Menhir beacon v1\n"
_CANONICAL_DOC_ROLES = {"entrypoint", "config"}
_MAX_CANONICAL_DOCS = 8
_MAX_CONCEPTS = 12
_SLUG_RE = re.compile(r"[^a-z0-9]+")


class BeaconGenerationError(ValueError):
    """Raised when required source evidence for a Beacon is unavailable."""


class BeaconProjectReader(Protocol):
    """The subset of StructureQueries generation reads; injectable for tests."""

    def get_project_root_path(self, project_name: str) -> str | None: ...

    def get_project_coverage(self, project_name: str) -> dict[str, Any]: ...

    def get_scan_fingerprint(self, project_name: str) -> str | None: ...

    def query_overview(self, project: str) -> dict[str, Any]: ...

    def query_files(self, project: str, path_filter: str = "") -> list[dict[str, str]]: ...

    def query_documents(self, project: str, path_filter: str = "", document_type: str | None = None) -> list[dict[str, str]]: ...


@dataclass(frozen=True)
class GenerationOutcome:
    output_path: Path
    sha256: str
    created: bool
    scan_fingerprint: str


def _slug(text: str) -> str:
    return _SLUG_RE.sub("-", text.strip().lower()).strip("-") or "project"


def _require_intact_index(reader: BeaconProjectReader, project: str, repo_root: Path) -> str:
    root = reader.get_project_root_path(project)
    if not root:
        raise BeaconGenerationError(f"project is not indexed (no root path): {project}")
    if Path(root).resolve() != repo_root.resolve():
        raise BeaconGenerationError(
            f"indexed root {root} does not match requested repository {repo_root}"
        )
    coverage = reader.get_project_coverage(project)
    if not coverage.get("known"):
        raise BeaconGenerationError(f"project coverage is unknown; re-ingest first: {project}")
    if coverage.get("partial_index"):
        raise BeaconGenerationError(f"project index is partial; complete an ingest first: {project}")
    fingerprint = reader.get_scan_fingerprint(project)
    if not fingerprint:
        raise BeaconGenerationError(f"project has no scan fingerprint; re-ingest first: {project}")
    return str(fingerprint)


def _select_canonical_docs(reader: BeaconProjectReader, project: str) -> list[dict[str, str]]:
    docs: list[dict[str, str]] = []
    for row in reader.query_documents(project):
        path = str(row.get("structure_path") or row.get("path") or "")
        title = str(row.get("title") or row.get("name") or "")
        if path:
            docs.append({"path": path, "title": title, "type": str(row.get("document_type") or "generic")})
    docs.sort(key=lambda d: (0 if d["path"] in ("README.md", ".agent/README.md") else 1, d["path"]))
    return docs[:_MAX_CANONICAL_DOCS]


def _structure_concept(overview: dict[str, Any], fingerprint: str) -> dict[str, Any]:
    entities = overview.get("entities") or {}
    edges = overview.get("edges") or {}
    parts = [f"{role}: {count}" for role, count in sorted(entities.items()) if count]
    edge_parts = [f"{rel}: {count}" for rel, count in sorted(edges.items()) if count]
    definition = (
        "Indexed repository structure as of the latest Menhir scan: "
        + "; ".join(parts + edge_parts)
    ).strip()
    return {
        "id": _slug("project-structure"),
        "name": "Project structure",
        "definition": definition or "Indexed repository structure.",
        "why_it_exists": "",
        "status": "current",
        "related_concepts": [],
        "implementation_locations": [],
        "sources": [{"type": "manifest", "title": "Menhir structure scan", "status": "current",
                     "path": "", "line_start": None, "line_end": None}],
        "_fingerprint": fingerprint,
    }


def build_raw_manifest(
    reader: BeaconProjectReader, project: str, repo_root: Path
) -> dict[str, Any]:
    """Build the raw beacon.yaml mapping strictly from indexed evidence; fail closed."""
    fingerprint = _require_intact_index(reader, project, repo_root)
    overview = reader.query_overview(project)
    description = str(overview.get("description") or "").strip()
    if not description:
        raise BeaconGenerationError(
            f"no indexed project description available; refusing to invent one: {project}"
        )
    docs = _select_canonical_docs(reader, project)
    if not docs:
        raise BeaconGenerationError(
            f"no indexed canonical documents available; refusing to invent docs: {project}"
        )
    files = reader.query_files(project)
    entrypoints = [f["path"] for f in files if f.get("role") == "entrypoint"]

    raw: dict[str, Any] = {
        "beacon_version": "0.1",
        "project": {
            "name": project,
            "tagline": "",
            "description": description,
            "status": "current",
            "repository": "",
            "primary_language": str(overview.get("stack") or ""),
            "license": "",
        },
        "purpose": {"one_sentence": description, "problem": "", "non_goals": []},
        "audiences": ["coding-agents"],
        "current_focus": [],
        "core_concepts": [_structure_concept(overview, fingerprint)],
        "canonical_docs": [
            {"path": d["path"], "role": "reference", "status": "current", "title": d["title"] or d["path"]}
            for d in docs
        ],
        "agent_guidance": {
            "read_first": [d["path"] for d in docs[:3]],
            "safe_first_tasks": [],
            "avoid_without_review": [],
            "expected_behavior": [],
        },
        "build_and_test": {
            "setup": "",
            "test": "",
            "benchmark": "",
        },
        "guardrails": [],
        "_entrypoints": entrypoints,
        "_scan_fingerprint": fingerprint,
    }
    return raw


def generate_beacon(
    reader: BeaconProjectReader,
    project: str,
    repo_root: Path,
    *,
    beacon_python: str,
    refresh: bool = False,
    expected_sha256: str | None = None,
) -> GenerationOutcome:
    """Generate or refresh the Beacon manifest for an indexed local project."""
    if bool(expected_sha256) != refresh:
        raise BeaconGenerationError(
            "refresh requires --expected-sha256; initial generation must not pass one"
        )
    beacon_python_is_usable(beacon_python)
    raw = build_raw_manifest(reader, project, repo_root)
    payload = build_manifest_via_beacon(beacon_python, raw, docs_root=repo_root)
    if not payload.startswith(GENERATED_PREFIX.encode("utf-8")):
        payload = GENERATED_PREFIX.encode("utf-8") + payload

    def validate(staged: Path) -> None:
        validate_manifest_file(beacon_python, staged)

    try:
        digest = publish_manifest(
            repo_root, payload, validate=validate, expected_sha256=expected_sha256
        )
    except PublicationError as exc:
        raise BeaconGenerationError(str(exc)) from exc
    except BeaconCompatError:
        raise
    target = repo_root / "beacon.generated.yaml"
    created = expected_sha256 is None
    return GenerationOutcome(
        output_path=target,
        sha256=digest,
        created=created,
        scan_fingerprint=str(raw["_scan_fingerprint"]),
    )
